### PR TITLE
Remove support for global default source on Mono

### PR DESCRIPTION
**Pull request by ChengTian**
@davidfowl @deepakaravindr 

Remove global default source on Mono

### CODE REVIEW

**Comment by ChengTian** [comment]
Verified this change with `dnu restore` on Mono and the bug is fixed

**Comment by ChengTian** [comment]
@davidfowl  @deepakaravindr , please sign off at your earliest convenience.

**Comment by ChengTian** [comment]
For dnxcore, we are going to use local application data folder. @davidfowl found a good way to get the path from environment variable. See https://github.com/mono/mono/blob/master/mcs/class/corlib/System/Environment.cs#L653.

I need to unblock myself with this PR and the change for dnxcore will be made in a separate PR

**Comment by emgarten** [comment]
:shipit:

**Pull request merged**
